### ISSUE TITLE
Change timeout setting as the command line parameter.

### ISSUE THREAD

**Issue by neerajnagpal0408** [brantburnett/couchbase-index-manager#101]
Hello

The network connectivity to our Couchbase servers is extremely slow and unpredictable at times, so I need to be able to change the timeout setting to very high value -- from the command line parameter. I use the following cmd, how can I raise the timeout for the following cmd.

couchbase-index-manager -c couchbase://x.x.x.x:8091 -u name -p password sync -f bucket_name xx123.yaml  --dry-run 

Regards

**Comment by brantburnett** [comment]
Currently, the only option that can be changed from the command line is the index build timeout, via `-t xxx`, and it defaults to 5 minutes. But it sounds like you'd like to change other timeouts like Couchbase connection and HTTP timeouts?

Most of the operations are done by the Couchbase NodeJS SDK under the hood. You might try adding additional settings to the connection string. I'm having a hard time finding clear documentation, but something like `-c couchbase://x.x.x.x:8091?n1ql_timeout=30.0&http_timeout=30.0`. Some of the settings are listed here: https://docs.couchbase.com/sdk-api/couchbase-c-client/group__lcb-cntl.html#ga1d1fd5115db3497211b6c9b6eec2af39

However, your best bet would be to run the index manager closer to the cluster. There is a Docker image you may use to easily execute the index manager closer to the cloud location where Couchbase resides, such as in a Kubernetes cluster.

**Comment by neerajnagpal0408** [comment]
Hello Thanks for your response, 

I am getting this error when issue the following error

RMML0514:Carnival neerajnagpal$ ~/Downloads/node_modules/couchbase-index-manager/bin/couchbase-index-manager -c couchbase://ipdclxcbshq001.ip.ocean.com:8091 -u nn1 -p nagpal sync -f xigppoc /Users/neerajnagpal/Carnival/CTASK0169273_IP_XIGPPoc.yaml  --dry-run --n1ql_timeout=30.0 --http_timeout=30.0
error: unknown option `--n1ql_timeout'
RMML0514:Carnival neerajnagpal$ ~/Downloads/node_modules/couchbase-index-manager/bin/couchbase-index-manager -c couchbase://ipdclxcbshq001.ip.ocean.com:8091 -u nn1 -p nagpal sync -f xigppoc /Users/neerajnagpal/Carnival/CTASK0169273_IP_XIGPPoc.yaml  --dry-run  --http_timeout=30.0
error: unknown option `--http_timeout'

**Comment by brantburnett** [comment]
You are attempting to pass command line options that don't exist. The options I mentioned before were connection string options, meant to be added to the connection string URL. Though I can't guarantee that would work, that's getting into NodeJS Couchbase SDK internals.
