### ISSUE TITLE
Couchbase Capella Connections - Client could not verify server's certificate

### ISSUE THREAD

**Issue by amfrye777** [brantburnett/couchbase-index-manager#102]
I am able to get capella connections to a trial cluster working with both the sdk doctor and a .net sdk application.
Running the 2.0.0 version of couchbase-index-manager, I get the below.
` Error: LCB_ERR_SSL_CANTVERIFY (1003): Client could not verify server's certificate`

**Comment by brantburnett** [comment]
I'll give this a look, it probably just needs an SDK  update to get the Capella certificates trusted.

**Comment by brantburnett** [comment]
I've fixed this with the SDK upgrade and tested. I'll cut a new release soon, but I noticed a couple of unrelated things in my testing that I want to double check first.

**Comment by brantburnett** [comment]
2.1.0 is now released with Capella compatibilty

**Comment by amfrye777** [comment]
I'm running into `Error: unambiguous_timeout` when running against my capella cluster. Not sure how to get more info for you than this. 
Verified again that a .net sdk application can connect fine... so there shouldn't be any issues in my configuration?

**Comment by brantburnett** [comment]
@amfrye777 Two quick thoughts:

1. Make sure you've whitelisted the IP where the job is running
2. Make sure you're using `couchbases://` instead of `couchbase://` in the connection string

Those were things that got me in my testing.

**Comment by amfrye777** [comment]
@brantburnett Aha! Here are some findings...
- ❌ It does not work with the dns srv url. Have tried `couchbases://` `https://` and neither work for me. 
- ❌  `https://` direct to one of the nodes does not work.
- ✔️  `couchbases://` direct to one of the nodes does work. 

seems like the dns srv url should work as well? I can connect either through dns srv or direct to a node using `couchbases://` from .net, so figured it would work similarly here.

**Comment by amfrye777** [comment]
Thanks for your quick turnaround on this! much appreciated!

**Comment by brantburnett** [comment]
> @brantburnett Aha! Here are some findings...
> 
> * ❌ It does not work with the dns srv url. Have tried `couchbases://` `https://` and neither work for me.
> * ❌  `https://` direct to one of the nodes does not work.
> * ✔️  `couchbases://` direct to one of the nodes does work.
> 
> seems like the dns srv url should work as well? I can connect either through dns srv or direct to a node using `couchbases://` from .net, so figured it would work similarly here.

That's interesting. Support for DNS SRV should be based on whatever the NodeJS SDK supports, it's doing all the connection lifting. Also, I'm pretty sure in my testing I was connecting using DNS SRV. I used the address from the "Connect" tab in Capella, not the individual node address.

Where were you getting the address? Also, what was your execution environment? I was testing from within a Linux docker container. It may also be worth opening a separate issue.

**Comment by amfrye777** [comment]
Where were you getting the address?  
> Cluster Connect tab in Capella. I use the same one from .net SDK and it works fine.  

Also, what was your execution environment? I was testing from within a Linux docker container. It may also be worth opening a separate issue.  
> I'm testing from a windows machine running node v14.17.6. I can easily test another node version if you would like. I have not tested from linux yet.

**Comment by amfrye777** [comment]
@brantburnett 
Update:
I tested using docker run command, and both dns srv and direct to node worked fine. This matched your successful tests. mentioned earlier.
I noticed the dockerfile was using node 16, so I switched to `v16.16.0` from windows. I experienced the same issue where I could not use the dns srv url from windows, but direct to node worked fine. 

Not sure if this is an issue with my windows environment setup or an SDK issue?

**Comment by amfrye777** [comment]
> @brantburnett Update: I tested using docker run command, and both dns srv and direct to node worked fine. This matched your successful tests. mentioned earlier. I noticed the dockerfile was using node 16, so I switched to `v16.16.0` from windows. I experienced the same issue where I could not use the dns srv url from windows, but direct to node worked fine.
> 
> Not sure if this is an issue with my windows environment setup or an SDK issue?

I’ll try to find time this week to test the node sdk locally from windows using their sample node sdk capella connection code. I’ll let you know how it goes.
