### ISSUE TITLE
Add soft fail capability

### ISSUE THREAD

**Issue by tcrozier** [brantburnett/couchbase-index-manager#12]
When running a sync against a definition file that contains an error it would be nice to have the ability to have it continue processing records instead of doing a hard fail. 
e.g. If a node defined in the node map is unreachable then continue processing the next record which may be on a reachable node.

**Comment by brantburnett** [comment]
This capability is already in place, all indexes which can be built will be built.  Then an error will be shown with the total number of failures, and the application will exit with an exit code of 1.
