### ISSUE TITLE
Change Nodes: display to show node from, node to

### ISSUE THREAD

**Issue by tcrozier** [brantburnett/couchbase-index-manager#21]
When you are using manual replication and change the node definition of both nodes for an index the plan will display the the final location of the index not where the index is currently defined and where it is being moved to.
E.G.
MyIndex is currently defined on index node 1 and 2 and I change the definition to be node 3 and 4

Currently it displays the following
Index sync plan:

Update: MyIndex
Nodes: couchbaseindex3.company.com:8091,couchbaseindex4.company.com:8091

Update: MyIndex_replica1
Nodes: couchbaseindex3.company.com:8091,couchbaseindex4.company.com:8091

What I would expect to see is:
Index sync plan:

Update: MyIndex
Nodes: couchbaseindex1.company.com:8091,couchbaseindex3.company.com:8091

Update: MyIndex_replica1
Nodes: couchbaseindex2.company.com:8091,couchbaseindex4.company.com:8091

**Comment by brantburnett** [comment]
Fixed in 0.4.1, output now looks like this:

```
Update: MyIndex
 Nodes: couchbaseindex1.company.com:8091
    ->: couchbaseindex3.company.com:8091

Update: MyIndex_replica1
 Nodes: couchbaseindex2.company.com:8091
    ->: couchbaseindex4.company.com:8091
```
