### ISSUE TITLE
Index wants to be recreated on version 0.6.0

### ISSUE THREAD

**Issue by tcrozier** [brantburnett/couchbase-index-manager#37]
Previously the following yaml description would create the index and would not try to recreate it.

```yaml
name: OrdersAdminInfo
index_key:
- siteId
- postedDate
- paymentInfo.paymentStatus
- orderCustomerInfo.email
condition: (`type` = 'order')
manual_replica: true
```

With version 0.6.0 it wants to recreate the index showing the following plan
Index sync plan:

```
Update: OrdersAdminInfo
  Keys: `siteId`,`postedDate`,`paymentInfo.paymentStatus`,`orderCustomerInfo.email`
     -> `siteId`,`postedDate`,(`paymentInfo`.`paymentStatus`),(`orderCustomerInfo`.`email`)
```

**Comment by brantburnett** [comment]
That plan is actually correct, because it's correcting an incorrect index from a previous version of couchbase-index-manager.  The spec on the last two keys is currently entirely wrapped with backticks, when it should be wrapping each segment in separate backtick delimiters.
