### ISSUE TITLE
Couchbase SyncGateway (SGW) - unable to add retain_deleted_xattr

### ISSUE THREAD

**Issue by atul-tewari** [brantburnett/couchbase-index-manager#53]
Hello Brant
We have a few SGW indexes we add to our couchbase cluster.  A few of those index definitions look like this:

`CREATE INDEX sg_roleAccess_x1 ON bucket_name ((all (array (op.name) for op in object_pairs((((meta().xattrs)._sync).role_access)) end))) WITH { "defer_build":true, "retain_deleted_xattr":true, "num_replica":1 }`

I used the following definition in the YAML file.  It creates the definition successfully but ignores `retain_deleted_attr: true`

`---`
`name: sg_roleAccess_x1`
`index_key:`
  `- (all (array (op.name) for op in object_pairs((((meta().xattrs)._sync).role_access)) end))`
`num_replica: 1`
`xattr: true`

I also tried using 
`retain_deleted_xattr: true`
`xattrs: true`
`xattr: true`

It ignores these fields completely.  Is there a way to add this attribute another way?

Thanks!

**Comment by brantburnett** [comment]
@atul-tewari 

Thanks for the feedback, support for this has been added in the new release 1.0.0-beta001. Documentation is in the readme, but it's pretty straightforward. Please let me know if you have any problems.

**Comment by atul-tewari** [comment]
Thank you Brant! Much much appreciated.
